services:
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017