services:
  server:
    build:
      context: .
      dockerfile: dockerfile.server
    restart: always
    volumes:
      - ./src/:/code/src/
    ports:
      - 80:80
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017