---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  labels:
    name: pvc-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage-mongo