---
apiVersion: v1
kind: Service
metadata:
  name: svc-fastapi
  labels:
    app: fastapi
spec:
  type: LoadBalancer
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80         # External port
      targetPort: 80   # Container port (matches Deployment)
      # nodePort: 30002  # Remove nodePort when using LoadBalancer
