---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  template:
    metadata:
      name: fastapi
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: lucianomarcosjr/fastapi:latest
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /docs
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /docs
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 0.5
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
