---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  labels:
    name: pv-mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-mongo
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/trade/fiap/k8s-fiap/data
