---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi
  name: svc-fastapi
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30002
  selector:
    app: fastapi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: svc-mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 30001
  selector:
    app: mongo
