# .github/workflows/block-commit.yml
name: Block Commits to Main Branch

on:
  push:
    branches:
      - main  # Specify which branch you want to block commits on
      - master

jobs:
  block_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Block commits
        run: |
          echo "Commits are not allowed on the main branch."
          exit 1  # Exit with a failure code to block the push
