name: TMS Project PROD Pipeline EKS

on:
  push:
    branches:
      - main
    paths:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # You can specify the Terraform version you're using

      - name: Initialize Terraform
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -migrate-state -lock-timeout=5m

      - name: Check if ECR Repository exists, then import or create
        run: |
          REPO_NAME="fastapi-server"
          REPO_CHECK=$(aws ecr describe-repositories --repository-names $REPO_NAME 2>&1 || true)
          
          if [[ $REPO_CHECK == *"RepositoryNotFoundException"* ]]; then
            echo "Repository does not exist, creating it..."
            terraform apply -target=aws_ecr_repository.api
          else
            echo "Repository exists, importing into Terraform..."
            terraform import aws_ecr_repository.api $REPO_NAME
          fi

      - name: Plan Terraform changes
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan


      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Gerar .env  
        run: |
          cat <<EOF > code/.env
          MONGODB_URL=${{ secrets.MONGODB_URL }}
          MERCADO_PAGO_TOKEN=${{ secrets.MERCADO_PAGO_TOKEN }}
          EOF

      - name: Build, tag, and push Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/fastapi-server:latest ./code
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/fastapi-server:latest 


      - name: Run Terraform apply to update Lambda
        env:
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name fastapi-cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy to Kubernetes
        run: |
          cd infra
          sed -i "s/latest/${{ github.sha }}/g" deployment.yaml
          kubectl apply -f deployment.yaml --validate=false