name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black  # Instala flake8 e black

      - name: Run lint
        run: |
          flake8 .  # Ou o diretório que contém o código

      - name: Format code
        run: |
          black --check .  # Verifica o código com black, sem alterar arquivos

      - name: Run tests
        run: |
          pytest
